### ISSUE TITLE
Check for forbidden file-types before creating torrent and uploading

### ISSUE THREAD

**Issue by TokenPTH** [pthcode/autotunes#1]
> The torrent contained one or more invalid files (Discogs.webloc)

It might be worth-while to implement Gazelle's routine that checks for forbidden file types inside the `.torrent`'s file list. Or at least catch this kind of error (I had to manually upload, to understand what was happening).

**Comment by zacharydenton** [comment]
Fixed by https://github.com/pthcode/autotunes/commit/5e7472eb455501be398b163dc66f6cef9b9f065c.
