### ISSUE TITLE
Proposal: Add {CD}/{WEB}/{Vinyl} to file name if we have no catalog number

### ISSUE THREAD

**Issue by TokenPTH** [pthcode/autotunes#2]
Too lazy to do a pull request, just mocking stuff up. If this is not considered an improvement, please ignore. Usually without catalog numbers it should be a WEB rip. I guess being explicit could help. (I don't mind, if we want to keep it simple instead)

````python
elif album.media:
    media = 'WEB' if album.media == 'digital' else album.media     # Not sure about capitalization
    path += " {" + media + "}"
````

**Comment by TokenPTH** [comment]
I just remembered, maybe even if there is a catalog number. The reason is that there are cases where two catalog numbers are identical and only vinyl/CD can be used to distinguish them.

Checking other releases for catalog number dupes sounds like a lot of code.

**Comment by zacharydenton** [comment]
Fixed by https://github.com/pthcode/autotunes/commit/5e7472eb455501be398b163dc66f6cef9b9f065c.
