### ISSUE TITLE
Parse the upload page error text instead of printing the entire page HTML

### ISSUE THREAD

**Issue by zacharydenton** [pthcode/autotunes#6]
If there was an error while uploading, print just the error message - not the entire page.

**Comment by TokenPTH** [comment]
Additionally, we should make some checks before uploading. Such as whether a year exists (if not, an error will be returned).

**Comment by zacharydenton** [comment]
Fixed by https://github.com/pthcode/autotunes/commit/5e7472eb455501be398b163dc66f6cef9b9f065c.
